version: "3"

services:
  teslamate4china:
    container_name: teslamate4china-service
    # image: i.bawfnje.work:8000/teslamate4china:latest
    # image: teslamate4china-service:latest
    build: ./
    # restart: always
    environment:
      - ENCRYPTION_KEY=Makelt8485Key #insert a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=Makelt8485secret #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    container_name: teslamate4china-database
    image: postgres:13
    # restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=Makelt8485secret #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - ./shell/data/teslamate-db:/var/lib/postgresql/data

  grafana:
    container_name: teslamate4china-grafana
    # image: i.bawfnje.work:8000/teslamate4china_grafana:latest
    # image: teslamate4china-grafana:latest
    build: ./grafana/
    # restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=Makelt8485secret #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=Makelt8485
      - GF_SECURITY_ADMIN_USER=bawfnje
      - GF_SECURITY_ADMIN_PASSWORD=Makelt8485
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - 3000:3000
    volumes:
      - ./shell/data/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    container_name: teslamate4china-proxy
    image: eclipse-mosquitto:2
    # restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
