version: "3"

services:
  portainer:
    # 需使用以下命令重置密码：docker run --rm -v  /var/lib/docker/volumes/portainer_data/_data:/data portainer/helper-reset-password 6053537/portainer-ce
    image: portainer/portainer-ce
    container_name: docker-portainer
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shell/data/portainer-data:/data
      # - ./shell/data/public:/public
  teslamate4china:
    container_name: teslamate4china-service
    # image: i.bawfnje.work:8000/teslamate4china:latest
    # image: dhuar/teslamate:latest
    build: ./
    # restart: always
    environment:
      - ENCRYPTION_KEY=Makelt8485Key #insert a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=Makelt8485secret #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=CN
    ports:
      - 4000:4000
    volumes:
      - ./shell/data/import:/opt/app/import
    cap_drop:
      - all

  database:
    container_name: teslamate4china-postgres
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=Makelt8485secret #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - ./shell/data/teslamate-db-15:/var/lib/postgresql/data

  grafana:
    container_name: teslamate4china-grafana
    # image: i.bawfnje.work:8000/teslamate4china_grafana:latest
    # image: dhuar/grafana:latest
    build: ./grafana/
    # restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=Makelt8485secret #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=Makelt8485
      - GF_SECURITY_ADMIN_USER=bawfnje
      - GF_SECURITY_ADMIN_PASSWORD=Makelt8485
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - 3000:3000
    volumes:
      - ./shell/data/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    container_name: teslamate4china-proxy
    image: eclipse-mosquitto:2
    # restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - ./shell/data/mosquitto-conf:/mosquitto/config
      - ./shell/data/mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
